allowBuilds:
  '@parcel/watcher': true
  '@prisma/client': true
  '@prisma/engines': true
  '@swc/core': true
  bcrypt: true
  esbuild: true
  prisma: true
  puppeteer: true
  sharp: true
  unrs-resolver: true
  vue-demi: true
